/* AUTO-GENERATED by scripts/gen-db-types.mjs — DO NOT EDIT BY HAND.
 * Regenerate with `pnpm db:types`. CI regenerates and fails if this differs. */

export const DB_SCHEMA_VERSION = "[\"audit_log\",\"driver_profiles\",\"sessions\",\"stop_photos\",\"stop_verifications\",\"stops\",\"throttle_records\",\"users\",\"vehicles\",\"verification_codes\"]";

export type DbColumn = { type: string; nullable: boolean; pg: string };

export type DbSchema = {
  audit_log: {
    id: {"type":"string","nullable":false,"pg":"uuid"},
    actor_id: {"type":"string","nullable":true,"pg":"uuid"},
    action: {"type":"string","nullable":false,"pg":"text"},
    target_type: {"type":"string","nullable":true,"pg":"text"},
    target_id: {"type":"string","nullable":true,"pg":"text"},
    before: {"type":"unknown","nullable":true,"pg":"jsonb"},
    after: {"type":"unknown","nullable":true,"pg":"jsonb"},
    reason: {"type":"string","nullable":true,"pg":"text"},
    created_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
  };
  driver_profiles: {
    id: {"type":"string","nullable":false,"pg":"uuid"},
    user_id: {"type":"string","nullable":false,"pg":"uuid"},
    status: {"type":"string","nullable":false,"pg":"text"},
    submitted_at: {"type":"Date","nullable":true,"pg":"timestamptz"},
    review_note: {"type":"string","nullable":true,"pg":"text"},
    created_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
    updated_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
  };
  sessions: {
    id: {"type":"string","nullable":false,"pg":"uuid"},
    user_id: {"type":"string","nullable":false,"pg":"uuid"},
    refresh_token_hash: {"type":"string","nullable":false,"pg":"text"},
    created_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
    expires_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
    revoked_at: {"type":"Date","nullable":true,"pg":"timestamptz"},
  };
  stop_photos: {
    id: {"type":"string","nullable":false,"pg":"uuid"},
    stop_id: {"type":"string","nullable":false,"pg":"uuid"},
    storage_key: {"type":"string","nullable":false,"pg":"text"},
    taken_at: {"type":"Date","nullable":true,"pg":"timestamptz"},
    created_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
    mime_type: {"type":"string","nullable":false,"pg":"text"},
  };
  stop_verifications: {
    id: {"type":"string","nullable":false,"pg":"uuid"},
    stop_id: {"type":"string","nullable":false,"pg":"uuid"},
    verifier_id: {"type":"string","nullable":false,"pg":"uuid"},
    decision: {"type":"string","nullable":false,"pg":"text"},
    reason: {"type":"string","nullable":true,"pg":"text"},
    device: {"type":"string","nullable":true,"pg":"text"},
    gps_accuracy_m: {"type":"number","nullable":true,"pg":"float8"},
    created_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
  };
  stops: {
    id: {"type":"string","nullable":false,"pg":"uuid"},
    code: {"type":"string","nullable":false,"pg":"text"},
    name_en: {"type":"string","nullable":false,"pg":"text"},
    name_ar: {"type":"string","nullable":false,"pg":"text"},
    lat: {"type":"number","nullable":false,"pg":"float8"},
    lng: {"type":"number","nullable":false,"pg":"float8"},
    status: {"type":"string","nullable":false,"pg":"text"},
    source: {"type":"string","nullable":false,"pg":"text"},
    created_by: {"type":"string","nullable":true,"pg":"uuid"},
    stand_ok: {"type":"boolean","nullable":true,"pg":"bool"},
    lit_ok: {"type":"boolean","nullable":true,"pg":"bool"},
    legal_stop_ok: {"type":"boolean","nullable":true,"pg":"bool"},
    reachable_ok: {"type":"boolean","nullable":true,"pg":"bool"},
    walking_to_next_m: {"type":"number","nullable":true,"pg":"float8"},
    override_reason: {"type":"string","nullable":true,"pg":"text"},
    created_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
    updated_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
    capture_id: {"type":"string","nullable":true,"pg":"text"},
    gps_accuracy_m: {"type":"number","nullable":true,"pg":"float8"},
  };
  throttle_records: {
    key: {"type":"string","nullable":false,"pg":"text"},
    hits: {"type":"unknown","nullable":false,"pg":"jsonb"},
    expires_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
    blocked_until: {"type":"Date","nullable":true,"pg":"timestamptz"},
  };
  users: {
    id: {"type":"string","nullable":false,"pg":"uuid"},
    email: {"type":"string","nullable":true,"pg":"text"},
    phone: {"type":"string","nullable":true,"pg":"text"},
    name: {"type":"string","nullable":false,"pg":"text"},
    role: {"type":"string","nullable":false,"pg":"text"},
    password_hash: {"type":"string","nullable":true,"pg":"text"},
    status: {"type":"string","nullable":false,"pg":"text"},
    created_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
    updated_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
    email_verified_at: {"type":"Date","nullable":true,"pg":"timestamptz"},
    is_system_admin: {"type":"boolean","nullable":false,"pg":"bool"},
    deleted_at: {"type":"Date","nullable":true,"pg":"timestamptz"},
  };
  vehicles: {
    id: {"type":"string","nullable":false,"pg":"uuid"},
    owner_user_id: {"type":"string","nullable":false,"pg":"uuid"},
    plate: {"type":"string","nullable":false,"pg":"text"},
    model: {"type":"string","nullable":false,"pg":"text"},
    colour: {"type":"string","nullable":false,"pg":"text"},
    fleet_label: {"type":"string","nullable":true,"pg":"text"},
    status: {"type":"string","nullable":false,"pg":"text"},
    created_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
    updated_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
  };
  verification_codes: {
    id: {"type":"string","nullable":false,"pg":"uuid"},
    kind: {"type":"string","nullable":false,"pg":"text"},
    channel: {"type":"string","nullable":false,"pg":"text"},
    target: {"type":"string","nullable":false,"pg":"text"},
    code_hash: {"type":"string","nullable":false,"pg":"text"},
    attempts: {"type":"number","nullable":false,"pg":"int4"},
    last_sent_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
    last_attempt_at: {"type":"Date","nullable":true,"pg":"timestamptz"},
    expires_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
    consumed_at: {"type":"Date","nullable":true,"pg":"timestamptz"},
    created_at: {"type":"Date","nullable":false,"pg":"timestamptz"},
  };
};

export const dbSchema = {} as DbSchema;

