/* AUTO-GENERATED by scripts/gen-db-types.mjs — DO NOT EDIT BY HAND.
 * Regenerate with `pnpm db:types`. CI regenerates and fails if this differs. */

export const DB_SCHEMA_VERSION = "[]";

export type DbColumn = { type: string; nullable: boolean; pg: string };

export type DbSchema = {
  // No domain tables yet (P0.5: migration 0001 enables PostGIS only).
};

export const dbSchema = {} as DbSchema;

