/* ══════════════════════════════════════════════════════════════════════
   Photo storage — ONE interface (§0.3), swappable per deployment. The local
   implementation writes to a directory (PHOTO_STORAGE_DIR); on Railway a
   volume is mounted there. Swapping to S3-compatible storage later is a
   one-file change behind the same interface. Storage keys are opaque strings;
   nothing else in the app reads the filesystem.                     */
import { createHash, randomBytes } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

export interface PhotoStorage {
  put(bytes: Buffer, mimeType: string): Promise<string>;  // returns the storage key
  get(key: string): Promise<Buffer | null>;
}

export class LocalPhotoStorage implements PhotoStorage {
  constructor(private readonly dir: string) {}

  private async ensureDir(): Promise<void> {
    await mkdir(resolve(this.dir), { recursive: true });
  }

  async put(bytes: Buffer, mimeType: string): Promise<string> {
    await this.ensureDir();
    const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 32);
    const key = `${hash}-${randomBytes(6).toString('hex')}${extFor(mimeType)}`;
    await writeFile(join(resolve(this.dir), key), bytes);
    return key;
  }

  async get(key: string): Promise<Buffer | null> {
    // storage keys are generated by put() and validated here — never a raw path
    if (!/^[a-f0-9-]+\.(jpg|jpeg|png|webp)$/i.test(key)) return null;
    try {
      return await readFile(join(resolve(this.dir), key));
    } catch {
      return null;
    }
  }
}

function extFor(mimeType: string): string {
  switch (mimeType.toLowerCase()) {
    case 'image/png': return '.png';
    case 'image/webp': return '.webp';
    case 'image/jpeg': return '.jpg';
    default: return '.jpg';
  }
}
